In [2]:
import numpy as np
import pandas as pd

In [49]:
#data1 = pd.read_csv('GeoFRED_All-Transactions_House_Price_Index_by_County_Index_2000=100.csv', delimiter =",")
#data1.head()

In [50]:
  # reading two csv files
data1 = pd.read_csv('GeoFRED_All-Transactions_House_Price_Index_by_County_Index_2000=100.csv')
data2 = pd.read_csv('GeoFRED_Equifax_Subprime_Credit_Population_by_County_Percent.csv')
data3 = pd.read_csv('GeoFRED_Equifax_Subprime_Credit_Population_by_County_Percent.csv')
data4 = pd.read_csv('GeoFRED_Housing_Inventory__Active_Listing_Count_by_County_Level.csv')
data5 = pd.read_csv('GeoFRED_Per_Capita_Personal_Income_by_County_Dollars (1).csv')
data6 = pd.read_csv('GeoFRED_Unemployment_Rate_by_County_Percent (1).csv')

In [51]:
big_concat = pd.concat([data1.set_index('Region Code'),data2.set_index('Region Code'), data3.set_index("Region Code"), data4.set_index("Region Code"), data5.set_index("Region Code"), data6.set_index("Region Code")], axis=1, join='inner').reset_index()

In [52]:
big_concat.head()

,Region Code,Series ID,Region Name,State,2010,2011,2012,2013,2014,2015,...,2018 Q4,2019 Q1,2019 Q2,2019 Q3,2019 Q4,2020 Q1,2020 Q2,2020 Q3,2020 Q4,2021 Q1
0,22001,ATNHPIUS22001A,Acadia Parish,LA,144.44,142.77,144.42,149.83,153.58,154.92,...,4.8,5.0,4.9,5.5,5.1,5.3,9.8,7.8,6.4,6.1
1,16001,ATNHPIUS16001A,Ada County,ID,124.83,110.20,115.45,129.05,142.79,152.52,...,2.3,2.9,2.2,2.3,2.2,2.5,9.5,5.6,4.1,3.8
2,42001,ATNHPIUS42001A,Adams County,PA,149.71,141.61,136.11,135.26,133.85,138.33,...,3.0,3.6,3.1,3.6,3.2,3.8,12.8,7.2,4.3,5.4
3,8001,ATNHPIUS08001A,Adams County,CO,100.37,96.17,99.10,107.68,123.21,140.02,...,3.1,3.4,2.7,2.7,2.5,3.9,12.6,8.1,7.6,7.6
4,17001,ATNHPIUS17001A,Adams County,IL,130.80,131.11,133.08,134.32,138.27,142.12,...,3.9,4.2,3.0,3.1,2.8,3.0,11.3,6.6,4.6,4.8

In [61]:
big_concat.index.is_unique

True

In [64]:
big_concat = big_concat.set_index("State")

In [66]:
big_concat

,Region Code,Series ID,Region Name,2010,2011,2012,2013,2014,2015,2016,...,2018 Q4,2019 Q1,2019 Q2,2019 Q3,2019 Q4,2020 Q1,2020 Q2,2020 Q3,2020 Q4,2021 Q1
State,,,,,,,,,,,,,,,,,,,,,
"( LA, LA, LA, LA, LA, LA)",22001,ATNHPIUS22001A,Acadia Parish,144.44,142.77,144.42,149.83,153.58,154.92,157.71,...,4.8,5.0,4.9,5.5,5.1,5.3,9.8,7.8,6.4,6.1
"( ID, ID, ID, ID, ID, ID)",16001,ATNHPIUS16001A,Ada County,124.83,110.20,115.45,129.05,142.79,152.52,165.94,...,2.3,2.9,2.2,2.3,2.2,2.5,9.5,5.6,4.1,3.8
"( PA, PA, PA, PA, PA, PA)",42001,ATNHPIUS42001A,Adams County,149.71,141.61,136.11,135.26,133.85,138.33,142.98,...,3.0,3.6,3.1,3.6,3.2,3.8,12.8,7.2,4.3,5.4
"( CO, CO, CO, CO, CO, CO)",8001,ATNHPIUS08001A,Adams County,100.37,96.17,99.10,107.68,123.21,140.02,158.65,...,3.1,3.4,2.7,2.7,2.5,3.9,12.6,8.1,7.6,7.6
"( IL, IL, IL, IL, IL, IL)",17001,ATNHPIUS17001A,Adams County,130.80,131.11,133.08,134.32,138.27,142.12,143.73,...,3.9,4.2,3.0,3.1,2.8,3.0,11.3,6.6,4.6,4.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"( ME, ME, ME, ME, ME, ME)",23031,ATNHPIUS23031A,York County,146.76,143.71,141.00,141.09,144.20,147.94,154.31,...,2.6,3.2,2.3,2.1,2.2,3.4,7.8,5.6,4.8,6.3
"( PA, PA, PA, PA, PA, PA)",42133,ATNHPIUS42133A,York County,140.57,134.01,127.84,127.57,129.17,131.76,133.88,...,3.5,4.0,3.7,4.2,3.8,4.4,13.5,8.7,5.5,6.4
"( SC, SC, SC, SC, SC, SC)",45091,ATNHPIUS45091A,York County,120.44,114.97,113.12,115.77,120.50,124.77,131.45,...,2.9,3.3,2.7,2.3,2.3,2.9,10.1,6.2,5.1,4.9
"( CA, CA, CA, CA, CA, CA)",6115,ATNHPIUS06115A,Yuba County,124.75,108.06,108.65,125.86,151.77,158.96,175.96,...,6.1,7.7,5.9,5.7,5.6,7.4,14.6,11.0,9.1,9.9
"( AZ, AZ, AZ, AZ, AZ, AZ)",4027,ATNHPIUS04027A,Yuma County,135.22,122.02,118.83,123.99,128.57,134.54,140.12,...,16.1,13.2,17.4,20.8,15.9,13.5,23.0,20.1,11.9,11.4

In [63]:
# Filter all rows for which the player's
# age is greater than or equal to 25
state_filtered = big_concat[big_concat['State'] == " GA"]
  
# Print the new dataframe
state_filtered.head(15)

ValueError: cannot reindex from a duplicate axis

In [6]:
hpi = pd.read_csv("HPI.csv")
hpi

,State,Region Code,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,SC,45001,132.29,128.12,123.05,123.16,130.71,131.96,133.75,142.15,152.61,152.99,165.44
1,LA,22001,144.44,142.77,144.42,149.83,153.58,154.92,157.71,160.82,162.84,168.98,170.25
2,VA,51001,171.86,167.34,163.35,162.22,160.17,163.32,163.24,168.20,165.83,171.98,182.96
3,ID,16001,124.83,110.20,115.45,129.05,142.79,152.52,165.94,184.58,209.58,233.07,254.81
4,MO,29001,112.61,113.79,116.24,116.75,118.19,117.48,119.61,121.36,127.29,128.14,128.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2390,VA,51199,178.80,170.74,165.77,168.15,170.16,171.43,174.93,176.56,182.91,181.72,190.53
2391,TX,48503,140.08,140.33,142.63,144.93,151.47,151.69,158.08,145.67,158.52,168.34,168.15
2392,CA,6115,124.75,108.06,108.65,125.86,151.77,158.96,175.96,196.02,210.85,225.28,239.18
2393,CO,8125,135.59,141.59,143.15,147.77,153.73,152.26,166.80,172.16,181.03,190.77,197.78
2394,AZ,4027,135.22,122.02,118.83,123.99,128.57,134.54,140.12,144.89,150.86,157.66,168.39

In [8]:
state_filtered = hpi[hpi['State'] == "GA"]
state_filtered

,State,Region Code,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
63,GA,13001,122.45,112.62,111.42,113.54,113.74,116.80,135.72,120.15,123.67,126.50,135.25
96,GA,13009,130.75,121.33,121.77,116.31,118.86,119.10,123.75,123.29,133.63,144.61,150.45
102,GA,13011,102.99,100.54,90.87,95.15,99.81,105.47,111.98,122.27,125.81,142.29,144.64
110,GA,13013,99.70,85.96,78.11,83.03,96.31,107.88,114.89,126.25,138.97,148.43,158.47
116,GA,13015,103.85,95.88,89.10,93.19,104.11,109.57,115.40,127.14,137.92,146.03,153.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2313,GA,13311,114.22,105.26,101.52,97.57,104.58,109.71,117.93,121.88,132.53,137.34,140.97
2318,GA,13313,114.53,106.79,103.74,105.54,111.94,114.00,117.87,125.26,133.75,139.20,147.54
2325,GA,13317,112.60,112.05,97.98,97.29,108.89,103.27,114.70,101.83,120.15,113.36,127.42
2328,GA,13319,112.19,99.70,107.58,98.47,121.27,107.70,119.08,115.24,113.43,116.97,117.22
2364,GA,13321,127.58,116.18,120.67,119.31,119.14,115.61,118.21,124.76,121.33,131.71,128.16